source :rubygems

gem 'sinatra'
gem 'haml'
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-transactions'
gem 'rest-client'
gem 'xml-simple'
gem 'pg'
gem 'awesome_print'
gem 'debugger'
gem 'dm-postgres-adapter'
